name: CI-Ejercicio

on: [push, pull_request] # Se activa con cada subida o PR

jobs:
  tarea-de-prueba:
    runs-on: ubuntu-latest # Usamos una máquina Linux de GitHub
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4 # Copia tu repo en la máquina virtual

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ejecutar el script de test
        run: npm test # Ejecuta el comando que definimos en el package.json
